version: '3.3'

services:
   mysql:
     image: mysql:5
     environment:
       - MYSQL_DATABASE=
       - MYSQL_USER=
       - MYSQL_ROOT_PASSWORD=
     ports:
       - '3306:3306'
     volumes:
       - ./mysql_data:/var/lib/mysql
volumes:
  mysql_data: {}